server:
  port: 18081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liyongqiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
  redisson:
    address: redis://127.0.0.1:6379
    password: root

#  kafka:
#    bootstrap-servers: 192.168.1.132:9092
#    consumer:
#      properties:
#        group-id: test-consumer-group
#        auto-offset-reset: earliest
#        enable-auto-commit: false
#        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      retries: 0
#      acks: 1
#      batch-size: 16384
#      properties:
#        linger:
#          ms: 0
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    listener:
#      missing-topics-fatal: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#xxl:
#  job:
#    accessToken:
#    executor:
#      appname: xxl-job-executor-lyq
#      ip: 192.168.1.132
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: -1
#      port: 8888
#    admin:
#      addresses: http://192.168.1.132:8080/xxl-job-admin
#
#



