server:
  port: 18081

spring:
  ## RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672  #  页面web端访问： localhost：15672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/liyongqiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      stat-view-servlet:
        url-pattern: /druid/*

mybatis:
  mapper-locations: classpath:/mapper/*.xml








