server:
  port: 18081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liyongqiang?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml

