server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liyongqiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      stat-view-servlet:
        url-pattern: /druid/*

mybatis:
  mapper-locations: classpath:/mapper/*.xml

xxl:
  job:
    accessToken:
    executor:
      appname: xxl-job-executor-lyq
      ip: 192.168.1.132
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 8888
    admin:
      addresses: http://192.168.1.132:8080/xxl-job-admin

